/**
 * Quotations shown one at a time on the welcome screen.
 *
 * Chosen for a school: learning, effort, character and patience, with a
 * bias toward voices a Pakistani school community would recognise —
 * Iqbal, Jinnah, Ibn Khaldun, Rumi, Saadi — alongside universal ones.
 * Kept to aphorisms and proverbs in wide circulation rather than extended
 * passages from living authors.
 *
 * Each is short enough to read in a glance: this is the thing a parent sees
 * while the portal loads, not an essay.
 */

export interface Quote {
  text: string;
  author: string;
}

export const QUOTES: Quote[] = [
  { text: "Nations are born in the hearts of poets; they prosper and die in the hands of politicians.", author: "Allama Iqbal" },
  { text: "Be not like the moth that burns itself; be like the candle that gives light.", author: "Allama Iqbal" },
  { text: "Raise yourself so high that God Himself asks you what you desire.", author: "Allama Iqbal" },
  { text: "The ultimate aim of the ego is not to see something, but to be something.", author: "Allama Iqbal" },
  { text: "Failure is not fatal until you surrender trying.", author: "Allama Iqbal" },
  { text: "Do not compare your life with others. You have no idea what their journey is about.", author: "Rumi" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
  { text: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", author: "Rumi" },
  { text: "The wound is the place where the light enters you.", author: "Rumi" },
  { text: "Patience is the key to joy.", author: "Rumi" },
  { text: "With faith, discipline and selfless devotion to duty, there is nothing worthwhile that you cannot achieve.", author: "Muhammad Ali Jinnah" },
  { text: "Think a hundred times before you take a decision, but once that decision is taken, stand by it as one man.", author: "Muhammad Ali Jinnah" },
  { text: "There is no power on earth that can undo Pakistan.", author: "Muhammad Ali Jinnah" },
  { text: "Education is a matter of life and death for our nation.", author: "Muhammad Ali Jinnah" },
  { text: "Expect the best, prepare for the worst.", author: "Muhammad Ali Jinnah" },
  { text: "The seeker of knowledge is a friend of God.", author: "Arabic proverb" },
  { text: "Seek knowledge from the cradle to the grave.", author: "Arabic proverb" },
  { text: "The ink of the scholar is more sacred than the blood of the martyr.", author: "Arabic proverb" },
  { text: "Knowledge is a treasure, but practice is the key to it.", author: "Arabic proverb" },
  { text: "He who has health has hope, and he who has hope has everything.", author: "Arabic proverb" },
  { text: "A man's dignity lies in his knowledge, not in his lineage.", author: "Ibn Khaldun" },
  { text: "The differences between people arise from the differences in their ways of making a living.", author: "Ibn Khaldun" },
  { text: "Human beings are children of their customs, not of their ancestors.", author: "Ibn Khaldun" },
  { text: "A little knowledge that acts is worth more than much knowledge that is idle.", author: "Khalil Gibran" },
  { text: "The teacher who is wise does not bid you enter the house of his wisdom, but leads you to the threshold of your own mind.", author: "Khalil Gibran" },
  { text: "Work is love made visible.", author: "Khalil Gibran" },
  { text: "Progress lies not in enhancing what is, but in advancing toward what will be.", author: "Khalil Gibran" },
  { text: "Have patience. All things are difficult before they become easy.", author: "Saadi Shirazi" },
  { text: "A traveller without observation is a bird without wings.", author: "Saadi Shirazi" },
  { text: "Whatever is produced in haste goes easily to waste.", author: "Saadi Shirazi" },
  { text: "The sons of Adam are limbs of one another, having been created of one essence.", author: "Saadi Shirazi" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "A good head and a good heart are always a formidable combination.", author: "Nelson Mandela" },
  { text: "One child, one teacher, one book and one pen can change the world.", author: "Malala Yousafzai" },
  { text: "Let us pick up our books and our pens. They are our most powerful weapons.", author: "Malala Yousafzai" },
  { text: "We realise the importance of our voices only when we are silenced.", author: "Malala Yousafzai" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "An ounce of practice is worth more than tons of preaching.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "Education is not the filling of a pail, but the lighting of a fire.", author: "W. B. Yeats" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "Educating the mind without educating the heart is no education at all.", author: "Aristotle" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates" },
  { text: "An unexamined life is not worth living.", author: "Socrates" },
  { text: "The beginning is the most important part of the work.", author: "Plato" },
  { text: "Do not train children to learn by force and harshness, but lead them by what amuses them.", author: "Plato" },
  { text: "Courage is knowing what not to fear.", author: "Plato" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Learning without thought is labour lost; thought without learning is perilous.", author: "Confucius" },
  { text: "When it is obvious that the goals cannot be reached, adjust the action steps.", author: "Confucius" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Lao Tzu" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Continuous effort, not strength or intelligence, is the key to unlocking our potential.", author: "Winston Churchill" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "I have not failed. I've just found ten thousand ways that won't work.", author: "Thomas Edison" },
  { text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "Anyone who has never made a mistake has never tried anything new.", author: "Albert Einstein" },
  { text: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein" },
  { text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Albert Einstein" },
  { text: "Try not to become a person of success, but rather a person of value.", author: "Albert Einstein" },
  { text: "The important thing is not to stop questioning.", author: "Albert Einstein" },
  { text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
  { text: "Be less curious about people and more curious about ideas.", author: "Marie Curie" },
  { text: "One never notices what has been done; one can only see what remains to be done.", author: "Marie Curie" },
  { text: "If I have seen further, it is by standing on the shoulders of giants.", author: "Isaac Newton" },
  { text: "Tact is the art of making a point without making an enemy.", author: "Isaac Newton" },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
  { text: "Science is a way of thinking much more than it is a body of knowledge.", author: "Carl Sagan" },
  { text: "The whole of science is nothing more than a refinement of everyday thinking.", author: "Albert Einstein" },
  { text: "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.", author: "Richard Feynman" },
  { text: "The first principle is that you must not fool yourself — and you are the easiest person to fool.", author: "Richard Feynman" },
  { text: "I would rather have questions that can't be answered than answers that can't be questioned.", author: "Richard Feynman" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
  { text: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
  { text: "I am a slow walker, but I never walk back.", author: "Abraham Lincoln" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "Do the best you can until you know better. Then when you know better, do better.", author: "Maya Angelou" },
  { text: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", author: "Maya Angelou" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Nothing worth having comes easy.", author: "Theodore Roosevelt" },
  { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
  { text: "The only limit to our realisation of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "A room without books is like a body without a soul.", author: "Cicero" },
  { text: "The authority of those who teach is often an obstacle to those who want to learn.", author: "Cicero" },
  { text: "While there's life, there's hope.", author: "Cicero" },
  { text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison" },
  { text: "A reader lives a thousand lives before he dies.", author: "Proverb" },
  { text: "Today a reader, tomorrow a leader.", author: "Margaret Fuller" },
  { text: "There is no friend as loyal as a book.", author: "Ernest Hemingway" },
  { text: "The more that you read, the more things you will know.", author: "Dr. Seuss" },
  { text: "You're never too old, too wacky, too wild, to pick up a book and read to a child.", author: "Dr. Seuss" },
  { text: "Books are a uniquely portable magic.", author: "Proverb" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
  { text: "Reading maketh a full man; conference a ready man; and writing an exact man.", author: "Francis Bacon" },
  { text: "Studies serve for delight, for ornament, and for ability.", author: "Francis Bacon" },
  { text: "He who opens a school door closes a prison.", author: "Victor Hugo" },
  { text: "Perseverance, secret of all triumphs.", author: "Victor Hugo" },
  { text: "There is nothing more powerful than an idea whose time has come.", author: "Victor Hugo" },
  { text: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
  { text: "The mind is not a vessel to be filled but a fire to be kindled.", author: "Plutarch" },
  { text: "What we learn with pleasure we never forget.", author: "Alfred Mercier" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Obstacles cannot crush me; every obstacle yields to stern resolve.", author: "Leonardo da Vinci" },
  { text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.", author: "Leonardo da Vinci" },
  { text: "Nothing is particularly hard if you divide it into small jobs.", author: "Henry Ford" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "Coming together is a beginning; keeping together is progress; working together is success.", author: "Henry Ford" },
  { text: "Anyone who stops learning is old, whether at twenty or eighty.", author: "Henry Ford" },
  { text: "Quality means doing it right when no one is looking.", author: "Henry Ford" },
  { text: "Excellence is never an accident. It is the result of high intention and intelligent effort.", author: "Aristotle" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Proverb" },
  { text: "Little by little, one travels far.", author: "Proverb" },
  { text: "A journey is best measured in friends, rather than miles.", author: "Tim Cahill" },
  { text: "Fall seven times, stand up eight.", author: "Japanese proverb" },
  { text: "Vision without action is a daydream. Action without vision is a nightmare.", author: "Japanese proverb" },
  { text: "The bamboo that bends is stronger than the oak that resists.", author: "Japanese proverb" },
  { text: "Better than a thousand days of diligent study is one day with a great teacher.", author: "Japanese proverb" },
  { text: "If you are planning for a year, sow rice; if for ten years, plant trees; if for a hundred years, educate people.", author: "Chinese proverb" },
  { text: "A gem cannot be polished without friction, nor a person perfected without trials.", author: "Chinese proverb" },
  { text: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese proverb" },
  { text: "Teachers open the door, but you must enter by yourself.", author: "Chinese proverb" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", author: "Chinese proverb" },
  { text: "Be not afraid of growing slowly; be afraid only of standing still.", author: "Chinese proverb" },
  { text: "Dig the well before you are thirsty.", author: "Chinese proverb" },
  { text: "A book is like a garden carried in the pocket.", author: "Chinese proverb" },
  { text: "He who asks a question is a fool for five minutes; he who does not ask remains a fool forever.", author: "Chinese proverb" },
  { text: "One generation plants the trees; another gets the shade.", author: "Chinese proverb" },
  { text: "Smooth seas do not make skilful sailors.", author: "African proverb" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African proverb" },
  { text: "It takes a village to raise a child.", author: "African proverb" },
  { text: "However long the night, the dawn will break.", author: "African proverb" },
  { text: "Wisdom is like a baobab tree; no one individual can embrace it.", author: "African proverb" },
  { text: "Knowledge is like a garden: if it is not cultivated, it cannot be harvested.", author: "African proverb" },
  { text: "Rain does not fall on one roof alone.", author: "African proverb" },
  { text: "Where there is a will, there is a way.", author: "English proverb" },
  { text: "Rome was not built in a day.", author: "English proverb" },
  { text: "Practice makes perfect.", author: "English proverb" },
  { text: "Slow and steady wins the race.", author: "Aesop" },
  { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop" },
  { text: "United we stand, divided we fall.", author: "Aesop" },
  { text: "In union there is strength.", author: "Aesop" },
  { text: "Honesty is the first chapter in the book of wisdom.", author: "Thomas Jefferson" },
  { text: "Determine never to be idle. It is wonderful how much may be done if we are always doing.", author: "Thomas Jefferson" },
  { text: "I'm a great believer in luck, and I find the harder I work the more I have of it.", author: "Thomas Jefferson" },
  { text: "Knowledge is power. Knowledge is safety. Knowledge is happiness.", author: "Thomas Jefferson" },
  { text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Success is to be measured not by position, but by the obstacles overcome.", author: "Booker T. Washington" },
  { text: "Excellence is to do a common thing in an uncommon way.", author: "Booker T. Washington" },
  { text: "Character, not circumstances, makes the person.", author: "Booker T. Washington" },
  { text: "You can't build a reputation on what you are going to do.", author: "Henry Ford" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Twenty years from now you will be more disappointed by the things you didn't do.", author: "Mark Twain" },
  { text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { text: "Continuous improvement is better than delayed perfection.", author: "Mark Twain" },
  { text: "Good manners will open doors that the best education cannot.", author: "Clarence Thomas" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Success is nothing more than a few simple disciplines practised every day.", author: "Jim Rohn" },
  { text: "Don't wish it were easier; wish you were better.", author: "Jim Rohn" },
  { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "There are no traffic jams along the extra mile.", author: "Zig Ziglar" },
  { text: "Your attitude, not your aptitude, will determine your altitude.", author: "Zig Ziglar" },
  { text: "It's not what you've got, it's what you use that makes a difference.", author: "Zig Ziglar" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { text: "If you want to build a ship, teach people to yearn for the vast and endless sea.", author: "Antoine de Saint-Exupéry" },
  { text: "What is essential is invisible to the eye.", author: "Antoine de Saint-Exupéry" },
  { text: "Perfection is achieved when there is nothing left to take away.", author: "Antoine de Saint-Exupéry" },
  { text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "Intellectual growth should commence at birth and cease only at death.", author: "Albert Einstein" },
  { text: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
  { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
  { text: "Teaching is the one profession that creates all other professions.", author: "Proverb" },
  { text: "A teacher affects eternity; he can never tell where his influence stops.", author: "Henry Adams" },
  { text: "The art of teaching is the art of assisting discovery.", author: "Mark Van Doren" },
  { text: "To teach is to learn twice.", author: "Joseph Joubert" },
  { text: "Children must be taught how to think, not what to think.", author: "Margaret Mead" },
  { text: "Never doubt that a small group of thoughtful citizens can change the world.", author: "Margaret Mead" },
  { text: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
  { text: "We do not learn from experience; we learn from reflecting on experience.", author: "John Dewey" },
  { text: "Give the pupils something to do, not something to learn.", author: "John Dewey" },
  { text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
  { text: "Without education, you are not going anywhere in this world.", author: "Malcolm X" },
  { text: "There is no greater education than one that is self-driven.", author: "Neil deGrasse Tyson" },
  { text: "The good thing about science is that it's true whether or not you believe in it.", author: "Neil deGrasse Tyson" },
  { text: "Curiosity is the wick in the candle of learning.", author: "William Arthur Ward" },
  { text: "The mediocre teacher tells. The great teacher inspires.", author: "William Arthur Ward" },
  { text: "Do more than belong: participate. Do more than care: help.", author: "William Arthur Ward" },
  { text: "Opportunities are like sunrises. If you wait too long, you miss them.", author: "William Arthur Ward" },
  { text: "Gratitude can transform common days into thanksgivings.", author: "William Arthur Ward" },
  { text: "Develop a passion for learning. If you do, you will never cease to grow.", author: "Anthony J. D'Angelo" },
  { text: "Learn as much as you can while you are young, since life becomes too busy later.", author: "Dana Stewart Scott" },
  { text: "An education isn't how much you have committed to memory, but knowing where to look.", author: "Anatole France" },
  { text: "Nine tenths of education is encouragement.", author: "Anatole France" },
  { text: "To accomplish great things, we must not only act, but also dream.", author: "Anatole France" },
  { text: "The whole art of teaching is only the art of awakening the natural curiosity of young minds.", author: "Anatole France" },
  { text: "The purpose of learning is growth, and our minds, unlike our bodies, can continue growing.", author: "Mortimer Adler" },
  { text: "The best teachers are those who show you where to look but don't tell you what to see.", author: "Alexandra K. Trenfor" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill" },
  { text: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Difficulties mastered are opportunities won.", author: "Winston Churchill" },
  { text: "Honesty is the best policy.", author: "Proverb" },
  { text: "Manners maketh man.", author: "William of Wykeham" },
  { text: "Character is doing the right thing when nobody is looking.", author: "J. C. Watts" },
  { text: "Integrity is choosing courage over comfort.", author: "Proverb" },
  { text: "Be more concerned with your character than your reputation.", author: "John Wooden" },
  { text: "It's what you learn after you know it all that counts.", author: "John Wooden" },
  { text: "Failure is not fatal, but failure to change might be.", author: "John Wooden" },
  { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { text: "Things turn out best for the people who make the best of the way things turn out.", author: "John Wooden" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "The truth is incontrovertible. Panic may resent it, but in the end, there it is.", author: "Winston Churchill" },
  { text: "Respect for ourselves guides our morals; respect for others guides our manners.", author: "Laurence Sterne" },
  { text: "Politeness costs nothing and gains everything.", author: "Mary Wortley Montagu" },
  { text: "Kind words can be short and easy to speak, but their echoes are truly endless.", author: "Mother Teresa" },
  { text: "If you can't feed a hundred people, then feed just one.", author: "Mother Teresa" },
  { text: "Not all of us can do great things. But we can do small things with great love.", author: "Mother Teresa" },
  { text: "Peace begins with a smile.", author: "Mother Teresa" },
  { text: "Do small things with great love.", author: "Mother Teresa" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { text: "Mistakes are proof that you are trying.", author: "Proverb" },
  { text: "Every accomplishment starts with the decision to try.", author: "Proverb" },
  { text: "Great things never came from comfort zones.", author: "Proverb" },
  { text: "Dream big. Start small. Act now.", author: "Robin Sharma" },
  { text: "Change is hard at first, messy in the middle and gorgeous at the end.", author: "Robin Sharma" },
  { text: "Starve your distractions, feed your focus.", author: "Proverb" },
  { text: "Small daily improvements are the key to staggering long-term results.", author: "Proverb" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin" },
  { text: "He that is good for making excuses is seldom good for anything else.", author: "Benjamin Franklin" },
  { text: "Diligence is the mother of good luck.", author: "Benjamin Franklin" },
  { text: "Genius without education is like silver in the mine.", author: "Benjamin Franklin" },
  { text: "The doorstep to the temple of wisdom is a knowledge of our own ignorance.", author: "Benjamin Franklin" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Enthusiasm is the mother of effort, and without it nothing great was ever achieved.", author: "Ralph Waldo Emerson" },
  { text: "Knowledge is the antidote to fear.", author: "Ralph Waldo Emerson" },
  { text: "The purpose of life is not to be happy. It is to be useful, to be honourable, to be compassionate.", author: "Ralph Waldo Emerson" },
  { text: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson" },
  { text: "Our chief want is someone who will inspire us to be what we know we could be.", author: "Ralph Waldo Emerson" },
  { text: "Go confidently in the direction of your dreams.", author: "Henry David Thoreau" },
  { text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "How vain it is to sit down to write when you have not stood up to live.", author: "Henry David Thoreau" },
  { text: "Never let formal education get in the way of your learning.", author: "Proverb" },
  { text: "Education is learning what you didn't even know you didn't know.", author: "Daniel J. Boorstin" },
  { text: "The greatest obstacle to discovery is not ignorance — it is the illusion of knowledge.", author: "Daniel J. Boorstin" },
  { text: "Anyone who has never made a mistake has never tried anything.", author: "Proverb" },
  { text: "A ship in harbour is safe, but that is not what ships are built for.", author: "John A. Shedd" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "Learning is not attained by chance. It must be sought for with ardour and diligence.", author: "Abigail Adams" },
  { text: "There is no elevator to success. You have to take the stairs.", author: "Proverb" },
  { text: "Be patient with yourself. Nothing in nature blooms all year.", author: "Proverb" },
  { text: "Every expert was once a disaster.", author: "Proverb" },
  { text: "Effort only fully releases its reward after a person refuses to quit.", author: "Napoleon Hill" },
  { text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill" },
  { text: "Whatever the mind can conceive and believe, it can achieve.", author: "Napoleon Hill" },
  { text: "Strength and growth come only through continuous effort and struggle.", author: "Napoleon Hill" },
  { text: "Do not wait; the time will never be just right.", author: "Napoleon Hill" },
  { text: "A goal is a dream with a deadline.", author: "Napoleon Hill" },
  { text: "Knowledge has to be improved, challenged and increased constantly, or it vanishes.", author: "Peter Drucker" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "What gets measured gets improved.", author: "Peter Drucker" },
  { text: "Efficiency is doing things right; effectiveness is doing the right things.", author: "Peter Drucker" },
  { text: "Reading without reflecting is like eating without digesting.", author: "Edmund Burke" },
  { text: "Nobody made a greater mistake than he who did nothing because he could do only a little.", author: "Edmund Burke" },
  { text: "Education is the cheap defence of nations.", author: "Edmund Burke" },
  { text: "The only thing necessary for the triumph of evil is for good people to do nothing.", author: "Edmund Burke" },
  { text: "Learning is the only thing the mind never exhausts, never fears and never regrets.", author: "Leonardo da Vinci" },
  { text: "Study without desire spoils the memory, and it retains nothing that it takes in.", author: "Leonardo da Vinci" },
  { text: "Time stays long enough for anyone who will use it.", author: "Leonardo da Vinci" },
  { text: "Poor is the pupil who does not surpass his master.", author: "Leonardo da Vinci" },
  { text: "Knowledge of the past and of the places of the earth is the ornament and food of the mind.", author: "Leonardo da Vinci" },
  { text: "Iron rusts from disuse; so does inaction sap the vigour of the mind.", author: "Leonardo da Vinci" },
  { text: "He who is fixed to a star does not change his mind.", author: "Leonardo da Vinci" },
  { text: "Fortune favours the prepared mind.", author: "Louis Pasteur" },
  { text: "Let me tell you the secret that has led me to my goal: my strength lies solely in my tenacity.", author: "Louis Pasteur" },
  { text: "Science knows no country, because knowledge belongs to humanity.", author: "Louis Pasteur" },
  { text: "There is no such thing as a stupid question.", author: "Carl Sagan" },
  { text: "We are made of star-stuff, and we have a way of learning about ourselves.", author: "Carl Sagan" },
  { text: "Imagination will often carry us to worlds that never were.", author: "Carl Sagan" },
  { text: "Books break the shackles of time.", author: "Carl Sagan" },
  { text: "Understanding is a kind of ecstasy.", author: "Carl Sagan" },
  { text: "Somewhere something incredible is waiting to be known.", author: "Blaise Pascal" },
  { text: "Kind words do not cost much, yet they accomplish much.", author: "Blaise Pascal" },
  { text: "Little minds are tamed by misfortune; great minds rise above it.", author: "Washington Irving" },
  { text: "Great things are not done by impulse, but by a series of small things brought together.", author: "Vincent van Gogh" },
  { text: "If you hear a voice within you say 'you cannot paint', then by all means paint, and that voice will be silenced.", author: "Vincent van Gogh" },
  { text: "I am seeking, I am striving, I am in it with all my heart.", author: "Vincent van Gogh" },
  { text: "What would life be if we had no courage to attempt anything?", author: "Vincent van Gogh" },
  { text: "Nothing is impossible; the word itself says 'I'm possible'.", author: "Audrey Hepburn" },
  { text: "As you grow older, you will discover that you have two hands: one for helping yourself, the other for helping others.", author: "Audrey Hepburn" },
  { text: "The most difficult thing is the decision to act; the rest is merely tenacity.", author: "Amelia Earhart" },
  { text: "Adventure is worthwhile in itself.", author: "Amelia Earhart" },
  { text: "Never interrupt someone doing what you said couldn't be done.", author: "Amelia Earhart" },
  { text: "A single dream is more powerful than a thousand realities.", author: "J. R. R. Tolkien" },
  { text: "Not all those who wander are lost.", author: "J. R. R. Tolkien" },
  { text: "Faithless is he that says farewell when the road darkens.", author: "J. R. R. Tolkien" },
  { text: "The wisest mind has something yet to learn.", author: "George Santayana" },
  { text: "Those who cannot remember the past are condemned to repeat it.", author: "George Santayana" },
  { text: "To be interested in the changing seasons is a happier state of mind than to be hopelessly in love with spring.", author: "George Santayana" },
  { text: "Knowledge is of no value unless you put it into practice.", author: "Anton Chekhov" },
  { text: "Any idiot can face a crisis; it is this day-to-day living that wears you out.", author: "Anton Chekhov" },
  { text: "The task of the modern educator is not to cut down jungles, but to irrigate deserts.", author: "C. S. Lewis" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C. S. Lewis" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C. S. Lewis" },
  { text: "Integrity is doing the right thing, even when no one is watching.", author: "C. S. Lewis" },
  { text: "Humility is not thinking less of yourself; it's thinking of yourself less.", author: "C. S. Lewis" },
  { text: "Courage is not simply one of the virtues, but the form of every virtue at the testing point.", author: "C. S. Lewis" },
  { text: "There are far better things ahead than any we leave behind.", author: "C. S. Lewis" },
  { text: "Education without values makes man a more clever devil.", author: "C. S. Lewis" },
  { text: "The function of education is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr." },
  { text: "Intelligence plus character — that is the goal of true education.", author: "Martin Luther King Jr." },
  { text: "If you can't fly then run, if you can't run then walk, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr." },
  { text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr." },
  { text: "The time is always right to do what is right.", author: "Martin Luther King Jr." },
  { text: "We may have all come on different ships, but we're in the same boat now.", author: "Martin Luther King Jr." },
  { text: "An individual has not started living until he can rise above the narrow confines of his individualistic concerns.", author: "Martin Luther King Jr." },
  { text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr." },
  { text: "Whatever affects one directly, affects all indirectly.", author: "Martin Luther King Jr." },
  { text: "Everybody can be great, because anybody can serve.", author: "Martin Luther King Jr." },
];

/**
 * Picks a quote pseudo-randomly from a seed.
 *
 * Seeded rather than `Math.random()` so a page render is deterministic: the
 * server and the client must agree on which quote to show, or React logs a
 * hydration mismatch and swaps the text out from under the reader. Each
 * visitor still gets a different one, because the seed comes from their
 * request.
 */
export function quoteForSeed(seed: number): Quote {
  // Mixing before the modulo — consecutive seeds otherwise walk the list in
  // order, so two people arriving a second apart would see neighbours.
  let x = seed >>> 0;
  x ^= x << 13;
  x ^= x >>> 17;
  x ^= x << 5;
  return QUOTES[Math.abs(x >>> 0) % QUOTES.length];
}
